### PR TITLE
add module path only when it is not empty

### PR DESCRIPTION
**Pull request by maksonlee**

### CODE REVIEW

**Comment by maksonlee** [comment]
i am not sure if i was doing right, in my case, the component path is an empty string, so i need to add check to prevent that issue file path doesn't start with "/", please help to verify it, thanks.

**Comment by SpOOnman** [comment]
I don't use sonar so I'm unable to verify it. Does this change work for you in production?

**Comment by maksonlee** [comment]
Yes, it do work for me in production.

**Comment by pjagielski** [comment]
It's already fixed in #118

**Pull request closed without merging**
